site_name: Gabriel Angelini-Knoll
site_url: https://gabeangeliniknoll.github.io/homepage/

nav:
    - Home: index.md
    - Research: research.md
    - Teaching: teaching.md
    - Talks: talks.md
    - Mentoring: mentoring.md

theme:
    name: cinder
    nav_style: dark
    disable_nav_previous_next: true
    disable_nav_search: true
    disable_footer: true

plugins: 
    - search

markdown_extensions:
    - attr_list
    - pymdownx.blocks.html
    - toc:
        toc_depth: 2
